# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lora-obstacles.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lora-obstacles.proto',
  package='vutura.obstacles',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14lora-obstacles.proto\x12\x10vutura.obstacles\x1a\x1bgoogle/protobuf/empty.proto\"=\n\x0cTagsResponse\x12-\n\tobstacles\x18\x01 \x03(\x0b\x32\x1a.vutura.obstacles.Obstacle\"\xcd\x02\n\x08Obstacle\x12\n\n\x02ID\x18\x01 \x01(\r\x12-\n\x04type\x18\x02 \x01(\x0e\x32\x1f.vutura.obstacles.Obstacle.Type\x12\x35\n\x08position\x18\x03 \x01(\x0b\x32#.vutura.obstacles.Obstacle.Position\x12/\n\x05\x66\x65nce\x18\x04 \x01(\x0b\x32 .vutura.obstacles.Obstacle.Fence\x1a\x41\n\x08Position\x12\x10\n\x08latitude\x18\x01 \x01(\x02\x12\x11\n\tlongitude\x18\x02 \x01(\x02\x12\x10\n\x08\x61ltitude\x18\x03 \x01(\x02\x1a\x31\n\x05\x46\x65nce\x12\x0e\n\x06radius\x18\x01 \x01(\r\x12\x0b\n\x03min\x18\x02 \x01(\r\x12\x0b\n\x03max\x18\x03 \x01(\r\"(\n\x04Type\x12\x10\n\x0c\x46IRE_FIGHTER\x10\x00\x12\x0e\n\nFIRE_TRUCK\x10\x01\"C\n\x10\x43ollisionWarning\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\n\n\x02ID\x18\x02 \x01(\r\x12\x10\n\x08\x64istance\x18\x03 \x01(\x02\"L\n\x11\x43ollisionWarnings\x12\x37\n\x0bwarningList\x18\x01 \x03(\x0b\x32\".vutura.obstacles.CollisionWarning2\x8e\x01\n\x0bTagsService\x12\x41\n\x07GetTags\x12\x16.google.protobuf.Empty\x1a\x1e.vutura.obstacles.TagsResponse\x12<\n\x06SetTag\x12\x1a.vutura.obstacles.Obstacle\x1a\x16.google.protobuf.Emptyb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])



_OBSTACLE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='vutura.obstacles.Obstacle.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FIRE_FIGHTER', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FIRE_TRUCK', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=428,
  serialized_end=468,
)
_sym_db.RegisterEnumDescriptor(_OBSTACLE_TYPE)


_TAGSRESPONSE = _descriptor.Descriptor(
  name='TagsResponse',
  full_name='vutura.obstacles.TagsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='obstacles', full_name='vutura.obstacles.TagsResponse.obstacles', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=132,
)


_OBSTACLE_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='vutura.obstacles.Obstacle.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='vutura.obstacles.Obstacle.Position.latitude', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='vutura.obstacles.Obstacle.Position.longitude', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='vutura.obstacles.Obstacle.Position.altitude', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=375,
)

_OBSTACLE_FENCE = _descriptor.Descriptor(
  name='Fence',
  full_name='vutura.obstacles.Obstacle.Fence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='radius', full_name='vutura.obstacles.Obstacle.Fence.radius', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min', full_name='vutura.obstacles.Obstacle.Fence.min', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max', full_name='vutura.obstacles.Obstacle.Fence.max', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=426,
)

_OBSTACLE = _descriptor.Descriptor(
  name='Obstacle',
  full_name='vutura.obstacles.Obstacle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='vutura.obstacles.Obstacle.ID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='vutura.obstacles.Obstacle.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='vutura.obstacles.Obstacle.position', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fence', full_name='vutura.obstacles.Obstacle.fence', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_OBSTACLE_POSITION, _OBSTACLE_FENCE, ],
  enum_types=[
    _OBSTACLE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=468,
)


_COLLISIONWARNING = _descriptor.Descriptor(
  name='CollisionWarning',
  full_name='vutura.obstacles.CollisionWarning',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='vutura.obstacles.CollisionWarning.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ID', full_name='vutura.obstacles.CollisionWarning.ID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distance', full_name='vutura.obstacles.CollisionWarning.distance', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=470,
  serialized_end=537,
)


_COLLISIONWARNINGS = _descriptor.Descriptor(
  name='CollisionWarnings',
  full_name='vutura.obstacles.CollisionWarnings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='warningList', full_name='vutura.obstacles.CollisionWarnings.warningList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=539,
  serialized_end=615,
)

_TAGSRESPONSE.fields_by_name['obstacles'].message_type = _OBSTACLE
_OBSTACLE_POSITION.containing_type = _OBSTACLE
_OBSTACLE_FENCE.containing_type = _OBSTACLE
_OBSTACLE.fields_by_name['type'].enum_type = _OBSTACLE_TYPE
_OBSTACLE.fields_by_name['position'].message_type = _OBSTACLE_POSITION
_OBSTACLE.fields_by_name['fence'].message_type = _OBSTACLE_FENCE
_OBSTACLE_TYPE.containing_type = _OBSTACLE
_COLLISIONWARNINGS.fields_by_name['warningList'].message_type = _COLLISIONWARNING
DESCRIPTOR.message_types_by_name['TagsResponse'] = _TAGSRESPONSE
DESCRIPTOR.message_types_by_name['Obstacle'] = _OBSTACLE
DESCRIPTOR.message_types_by_name['CollisionWarning'] = _COLLISIONWARNING
DESCRIPTOR.message_types_by_name['CollisionWarnings'] = _COLLISIONWARNINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TagsResponse = _reflection.GeneratedProtocolMessageType('TagsResponse', (_message.Message,), dict(
  DESCRIPTOR = _TAGSRESPONSE,
  __module__ = 'lora_obstacles_pb2'
  # @@protoc_insertion_point(class_scope:vutura.obstacles.TagsResponse)
  ))
_sym_db.RegisterMessage(TagsResponse)

Obstacle = _reflection.GeneratedProtocolMessageType('Obstacle', (_message.Message,), dict(

  Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), dict(
    DESCRIPTOR = _OBSTACLE_POSITION,
    __module__ = 'lora_obstacles_pb2'
    # @@protoc_insertion_point(class_scope:vutura.obstacles.Obstacle.Position)
    ))
  ,

  Fence = _reflection.GeneratedProtocolMessageType('Fence', (_message.Message,), dict(
    DESCRIPTOR = _OBSTACLE_FENCE,
    __module__ = 'lora_obstacles_pb2'
    # @@protoc_insertion_point(class_scope:vutura.obstacles.Obstacle.Fence)
    ))
  ,
  DESCRIPTOR = _OBSTACLE,
  __module__ = 'lora_obstacles_pb2'
  # @@protoc_insertion_point(class_scope:vutura.obstacles.Obstacle)
  ))
_sym_db.RegisterMessage(Obstacle)
_sym_db.RegisterMessage(Obstacle.Position)
_sym_db.RegisterMessage(Obstacle.Fence)

CollisionWarning = _reflection.GeneratedProtocolMessageType('CollisionWarning', (_message.Message,), dict(
  DESCRIPTOR = _COLLISIONWARNING,
  __module__ = 'lora_obstacles_pb2'
  # @@protoc_insertion_point(class_scope:vutura.obstacles.CollisionWarning)
  ))
_sym_db.RegisterMessage(CollisionWarning)

CollisionWarnings = _reflection.GeneratedProtocolMessageType('CollisionWarnings', (_message.Message,), dict(
  DESCRIPTOR = _COLLISIONWARNINGS,
  __module__ = 'lora_obstacles_pb2'
  # @@protoc_insertion_point(class_scope:vutura.obstacles.CollisionWarnings)
  ))
_sym_db.RegisterMessage(CollisionWarnings)



_TAGSSERVICE = _descriptor.ServiceDescriptor(
  name='TagsService',
  full_name='vutura.obstacles.TagsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=618,
  serialized_end=760,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTags',
    full_name='vutura.obstacles.TagsService.GetTags',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_TAGSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetTag',
    full_name='vutura.obstacles.TagsService.SetTag',
    index=1,
    containing_service=None,
    input_type=_OBSTACLE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TAGSSERVICE)

DESCRIPTOR.services_by_name['TagsService'] = _TAGSSERVICE

# @@protoc_insertion_point(module_scope)
