// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: lora-obstacles.proto

#include "lora-obstacles.pb.h"
#include "lora-obstacles.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>
namespace vutura {
namespace obstacles {

static const char* TagsService_method_names[] = {
  "/vutura.obstacles.TagsService/GetTags",
  "/vutura.obstacles.TagsService/SetTag",
  "/vutura.obstacles.TagsService/GetWarnings",
  "/vutura.obstacles.TagsService/SetWarning",
};

std::unique_ptr< TagsService::Stub> TagsService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  std::unique_ptr< TagsService::Stub> stub(new TagsService::Stub(channel));
  return stub;
}

TagsService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetTags_(TagsService_method_names[0], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetTag_(TagsService_method_names[1], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetWarnings_(TagsService_method_names[2], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetWarning_(TagsService_method_names[3], ::grpc::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TagsService::Stub::GetTags(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::vutura::obstacles::TagsResponse* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_GetTags_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::vutura::obstacles::TagsResponse>* TagsService::Stub::AsyncGetTagsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::vutura::obstacles::TagsResponse>(channel_.get(), cq, rpcmethod_GetTags_, context, request);
}

::grpc::Status TagsService::Stub::SetTag(::grpc::ClientContext* context, const ::vutura::obstacles::Obstacle& request, ::google::protobuf::Empty* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_SetTag_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TagsService::Stub::AsyncSetTagRaw(::grpc::ClientContext* context, const ::vutura::obstacles::Obstacle& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>(channel_.get(), cq, rpcmethod_SetTag_, context, request);
}

::grpc::Status TagsService::Stub::GetWarnings(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::vutura::obstacles::CollisionWarnings* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_GetWarnings_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::vutura::obstacles::CollisionWarnings>* TagsService::Stub::AsyncGetWarningsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::vutura::obstacles::CollisionWarnings>(channel_.get(), cq, rpcmethod_GetWarnings_, context, request);
}

::grpc::Status TagsService::Stub::SetWarning(::grpc::ClientContext* context, const ::vutura::obstacles::CollisionWarning& request, ::google::protobuf::Empty* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_SetWarning_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TagsService::Stub::AsyncSetWarningRaw(::grpc::ClientContext* context, const ::vutura::obstacles::CollisionWarning& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>(channel_.get(), cq, rpcmethod_SetWarning_, context, request);
}

TagsService::Service::Service() {
  AddMethod(new ::grpc::RpcServiceMethod(
      TagsService_method_names[0],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< TagsService::Service, ::google::protobuf::Empty, ::vutura::obstacles::TagsResponse>(
          std::mem_fn(&TagsService::Service::GetTags), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      TagsService_method_names[1],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< TagsService::Service, ::vutura::obstacles::Obstacle, ::google::protobuf::Empty>(
          std::mem_fn(&TagsService::Service::SetTag), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      TagsService_method_names[2],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< TagsService::Service, ::google::protobuf::Empty, ::vutura::obstacles::CollisionWarnings>(
          std::mem_fn(&TagsService::Service::GetWarnings), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      TagsService_method_names[3],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< TagsService::Service, ::vutura::obstacles::CollisionWarning, ::google::protobuf::Empty>(
          std::mem_fn(&TagsService::Service::SetWarning), this)));
}

TagsService::Service::~Service() {
}

::grpc::Status TagsService::Service::GetTags(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::vutura::obstacles::TagsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TagsService::Service::SetTag(::grpc::ServerContext* context, const ::vutura::obstacles::Obstacle* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TagsService::Service::GetWarnings(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::vutura::obstacles::CollisionWarnings* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TagsService::Service::SetWarning(::grpc::ServerContext* context, const ::vutura::obstacles::CollisionWarning* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace vutura
}  // namespace obstacles

