// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lora-obstacles.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_lora_2dobstacles_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_lora_2dobstacles_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3008000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3008000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_lora_2dobstacles_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_lora_2dobstacles_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[7]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_lora_2dobstacles_2eproto;
namespace vutura {
namespace obstacles {
class CollisionWarning;
class CollisionWarningDefaultTypeInternal;
extern CollisionWarningDefaultTypeInternal _CollisionWarning_default_instance_;
class CollisionWarnings;
class CollisionWarningsDefaultTypeInternal;
extern CollisionWarningsDefaultTypeInternal _CollisionWarnings_default_instance_;
class Empty;
class EmptyDefaultTypeInternal;
extern EmptyDefaultTypeInternal _Empty_default_instance_;
class Obstacle;
class ObstacleDefaultTypeInternal;
extern ObstacleDefaultTypeInternal _Obstacle_default_instance_;
class Obstacle_Fence;
class Obstacle_FenceDefaultTypeInternal;
extern Obstacle_FenceDefaultTypeInternal _Obstacle_Fence_default_instance_;
class Obstacle_Position;
class Obstacle_PositionDefaultTypeInternal;
extern Obstacle_PositionDefaultTypeInternal _Obstacle_Position_default_instance_;
class TagsResponse;
class TagsResponseDefaultTypeInternal;
extern TagsResponseDefaultTypeInternal _TagsResponse_default_instance_;
}  // namespace obstacles
}  // namespace vutura
PROTOBUF_NAMESPACE_OPEN
template<> ::vutura::obstacles::CollisionWarning* Arena::CreateMaybeMessage<::vutura::obstacles::CollisionWarning>(Arena*);
template<> ::vutura::obstacles::CollisionWarnings* Arena::CreateMaybeMessage<::vutura::obstacles::CollisionWarnings>(Arena*);
template<> ::vutura::obstacles::Empty* Arena::CreateMaybeMessage<::vutura::obstacles::Empty>(Arena*);
template<> ::vutura::obstacles::Obstacle* Arena::CreateMaybeMessage<::vutura::obstacles::Obstacle>(Arena*);
template<> ::vutura::obstacles::Obstacle_Fence* Arena::CreateMaybeMessage<::vutura::obstacles::Obstacle_Fence>(Arena*);
template<> ::vutura::obstacles::Obstacle_Position* Arena::CreateMaybeMessage<::vutura::obstacles::Obstacle_Position>(Arena*);
template<> ::vutura::obstacles::TagsResponse* Arena::CreateMaybeMessage<::vutura::obstacles::TagsResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace vutura {
namespace obstacles {

enum Obstacle_Type : int {
  Obstacle_Type_UNIDENTIFIED_OBJECT = 0,
  Obstacle_Type_FIRE_FIGHTER = 1,
  Obstacle_Type_FIRE_TRUCK = 2,
  Obstacle_Type_FIRE_UAV = 3,
  Obstacle_Type_UNIDENTIFIED_UAV = 4,
  Obstacle_Type_Obstacle_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Obstacle_Type_Obstacle_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool Obstacle_Type_IsValid(int value);
constexpr Obstacle_Type Obstacle_Type_Type_MIN = Obstacle_Type_UNIDENTIFIED_OBJECT;
constexpr Obstacle_Type Obstacle_Type_Type_MAX = Obstacle_Type_UNIDENTIFIED_UAV;
constexpr int Obstacle_Type_Type_ARRAYSIZE = Obstacle_Type_Type_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Obstacle_Type_descriptor();
template<typename T>
inline const std::string& Obstacle_Type_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Obstacle_Type>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Obstacle_Type_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Obstacle_Type_descriptor(), enum_t_value);
}
inline bool Obstacle_Type_Parse(
    const std::string& name, Obstacle_Type* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Obstacle_Type>(
    Obstacle_Type_descriptor(), name, value);
}
// ===================================================================

class Empty :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vutura.obstacles.Empty) */ {
 public:
  Empty();
  virtual ~Empty();

  Empty(const Empty& from);
  Empty(Empty&& from) noexcept
    : Empty() {
    *this = ::std::move(from);
  }

  inline Empty& operator=(const Empty& from) {
    CopyFrom(from);
    return *this;
  }
  inline Empty& operator=(Empty&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Empty& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Empty* internal_default_instance() {
    return reinterpret_cast<const Empty*>(
               &_Empty_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Empty* other);
  friend void swap(Empty& a, Empty& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Empty* New() const final {
    return CreateMaybeMessage<Empty>(nullptr);
  }

  Empty* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Empty>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Empty& from);
  void MergeFrom(const Empty& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Empty* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vutura.obstacles.Empty";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_lora_2dobstacles_2eproto);
    return ::descriptor_table_lora_2dobstacles_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:vutura.obstacles.Empty)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_lora_2dobstacles_2eproto;
};
// -------------------------------------------------------------------

class TagsResponse :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vutura.obstacles.TagsResponse) */ {
 public:
  TagsResponse();
  virtual ~TagsResponse();

  TagsResponse(const TagsResponse& from);
  TagsResponse(TagsResponse&& from) noexcept
    : TagsResponse() {
    *this = ::std::move(from);
  }

  inline TagsResponse& operator=(const TagsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline TagsResponse& operator=(TagsResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TagsResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TagsResponse* internal_default_instance() {
    return reinterpret_cast<const TagsResponse*>(
               &_TagsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(TagsResponse* other);
  friend void swap(TagsResponse& a, TagsResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TagsResponse* New() const final {
    return CreateMaybeMessage<TagsResponse>(nullptr);
  }

  TagsResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TagsResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TagsResponse& from);
  void MergeFrom(const TagsResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TagsResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vutura.obstacles.TagsResponse";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_lora_2dobstacles_2eproto);
    return ::descriptor_table_lora_2dobstacles_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .vutura.obstacles.Obstacle obstacles = 1;
  int obstacles_size() const;
  void clear_obstacles();
  static const int kObstaclesFieldNumber = 1;
  ::vutura::obstacles::Obstacle* mutable_obstacles(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vutura::obstacles::Obstacle >*
      mutable_obstacles();
  const ::vutura::obstacles::Obstacle& obstacles(int index) const;
  ::vutura::obstacles::Obstacle* add_obstacles();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vutura::obstacles::Obstacle >&
      obstacles() const;

  // @@protoc_insertion_point(class_scope:vutura.obstacles.TagsResponse)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vutura::obstacles::Obstacle > obstacles_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_lora_2dobstacles_2eproto;
};
// -------------------------------------------------------------------

class Obstacle_Position :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vutura.obstacles.Obstacle.Position) */ {
 public:
  Obstacle_Position();
  virtual ~Obstacle_Position();

  Obstacle_Position(const Obstacle_Position& from);
  Obstacle_Position(Obstacle_Position&& from) noexcept
    : Obstacle_Position() {
    *this = ::std::move(from);
  }

  inline Obstacle_Position& operator=(const Obstacle_Position& from) {
    CopyFrom(from);
    return *this;
  }
  inline Obstacle_Position& operator=(Obstacle_Position&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Obstacle_Position& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Obstacle_Position* internal_default_instance() {
    return reinterpret_cast<const Obstacle_Position*>(
               &_Obstacle_Position_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(Obstacle_Position* other);
  friend void swap(Obstacle_Position& a, Obstacle_Position& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Obstacle_Position* New() const final {
    return CreateMaybeMessage<Obstacle_Position>(nullptr);
  }

  Obstacle_Position* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Obstacle_Position>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Obstacle_Position& from);
  void MergeFrom(const Obstacle_Position& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Obstacle_Position* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vutura.obstacles.Obstacle.Position";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_lora_2dobstacles_2eproto);
    return ::descriptor_table_lora_2dobstacles_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float latitude = 1;
  void clear_latitude();
  static const int kLatitudeFieldNumber = 1;
  float latitude() const;
  void set_latitude(float value);

  // float longitude = 2;
  void clear_longitude();
  static const int kLongitudeFieldNumber = 2;
  float longitude() const;
  void set_longitude(float value);

  // float altitude = 3;
  void clear_altitude();
  static const int kAltitudeFieldNumber = 3;
  float altitude() const;
  void set_altitude(float value);

  // @@protoc_insertion_point(class_scope:vutura.obstacles.Obstacle.Position)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  float latitude_;
  float longitude_;
  float altitude_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_lora_2dobstacles_2eproto;
};
// -------------------------------------------------------------------

class Obstacle_Fence :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vutura.obstacles.Obstacle.Fence) */ {
 public:
  Obstacle_Fence();
  virtual ~Obstacle_Fence();

  Obstacle_Fence(const Obstacle_Fence& from);
  Obstacle_Fence(Obstacle_Fence&& from) noexcept
    : Obstacle_Fence() {
    *this = ::std::move(from);
  }

  inline Obstacle_Fence& operator=(const Obstacle_Fence& from) {
    CopyFrom(from);
    return *this;
  }
  inline Obstacle_Fence& operator=(Obstacle_Fence&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Obstacle_Fence& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Obstacle_Fence* internal_default_instance() {
    return reinterpret_cast<const Obstacle_Fence*>(
               &_Obstacle_Fence_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(Obstacle_Fence* other);
  friend void swap(Obstacle_Fence& a, Obstacle_Fence& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Obstacle_Fence* New() const final {
    return CreateMaybeMessage<Obstacle_Fence>(nullptr);
  }

  Obstacle_Fence* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Obstacle_Fence>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Obstacle_Fence& from);
  void MergeFrom(const Obstacle_Fence& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Obstacle_Fence* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vutura.obstacles.Obstacle.Fence";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_lora_2dobstacles_2eproto);
    return ::descriptor_table_lora_2dobstacles_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 radius = 1;
  void clear_radius();
  static const int kRadiusFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::uint32 radius() const;
  void set_radius(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // uint32 min = 2;
  void clear_min();
  static const int kMinFieldNumber = 2;
  ::PROTOBUF_NAMESPACE_ID::uint32 min() const;
  void set_min(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // uint32 max = 3;
  void clear_max();
  static const int kMaxFieldNumber = 3;
  ::PROTOBUF_NAMESPACE_ID::uint32 max() const;
  void set_max(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // @@protoc_insertion_point(class_scope:vutura.obstacles.Obstacle.Fence)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::uint32 radius_;
  ::PROTOBUF_NAMESPACE_ID::uint32 min_;
  ::PROTOBUF_NAMESPACE_ID::uint32 max_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_lora_2dobstacles_2eproto;
};
// -------------------------------------------------------------------

class Obstacle :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vutura.obstacles.Obstacle) */ {
 public:
  Obstacle();
  virtual ~Obstacle();

  Obstacle(const Obstacle& from);
  Obstacle(Obstacle&& from) noexcept
    : Obstacle() {
    *this = ::std::move(from);
  }

  inline Obstacle& operator=(const Obstacle& from) {
    CopyFrom(from);
    return *this;
  }
  inline Obstacle& operator=(Obstacle&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Obstacle& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Obstacle* internal_default_instance() {
    return reinterpret_cast<const Obstacle*>(
               &_Obstacle_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(Obstacle* other);
  friend void swap(Obstacle& a, Obstacle& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Obstacle* New() const final {
    return CreateMaybeMessage<Obstacle>(nullptr);
  }

  Obstacle* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Obstacle>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Obstacle& from);
  void MergeFrom(const Obstacle& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Obstacle* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vutura.obstacles.Obstacle";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_lora_2dobstacles_2eproto);
    return ::descriptor_table_lora_2dobstacles_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Obstacle_Position Position;
  typedef Obstacle_Fence Fence;

  typedef Obstacle_Type Type;
  static constexpr Type UNIDENTIFIED_OBJECT =
    Obstacle_Type_UNIDENTIFIED_OBJECT;
  static constexpr Type FIRE_FIGHTER =
    Obstacle_Type_FIRE_FIGHTER;
  static constexpr Type FIRE_TRUCK =
    Obstacle_Type_FIRE_TRUCK;
  static constexpr Type FIRE_UAV =
    Obstacle_Type_FIRE_UAV;
  static constexpr Type UNIDENTIFIED_UAV =
    Obstacle_Type_UNIDENTIFIED_UAV;
  static inline bool Type_IsValid(int value) {
    return Obstacle_Type_IsValid(value);
  }
  static constexpr Type Type_MIN =
    Obstacle_Type_Type_MIN;
  static constexpr Type Type_MAX =
    Obstacle_Type_Type_MAX;
  static constexpr int Type_ARRAYSIZE =
    Obstacle_Type_Type_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Type_descriptor() {
    return Obstacle_Type_descriptor();
  }
  template<typename T>
  static inline const std::string& Type_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Type>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Type_Name.");
    return Obstacle_Type_Name(enum_t_value);
  }
  static inline bool Type_Parse(const std::string& name,
      Type* value) {
    return Obstacle_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // .vutura.obstacles.Obstacle.Position position = 3;
  bool has_position() const;
  void clear_position();
  static const int kPositionFieldNumber = 3;
  const ::vutura::obstacles::Obstacle_Position& position() const;
  ::vutura::obstacles::Obstacle_Position* release_position();
  ::vutura::obstacles::Obstacle_Position* mutable_position();
  void set_allocated_position(::vutura::obstacles::Obstacle_Position* position);

  // .vutura.obstacles.Obstacle.Fence fence = 4;
  bool has_fence() const;
  void clear_fence();
  static const int kFenceFieldNumber = 4;
  const ::vutura::obstacles::Obstacle_Fence& fence() const;
  ::vutura::obstacles::Obstacle_Fence* release_fence();
  ::vutura::obstacles::Obstacle_Fence* mutable_fence();
  void set_allocated_fence(::vutura::obstacles::Obstacle_Fence* fence);

  // uint32 ID = 1;
  void clear_id();
  static const int kIDFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::uint32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // .vutura.obstacles.Obstacle.Type type = 2;
  void clear_type();
  static const int kTypeFieldNumber = 2;
  ::vutura::obstacles::Obstacle_Type type() const;
  void set_type(::vutura::obstacles::Obstacle_Type value);

  // @@protoc_insertion_point(class_scope:vutura.obstacles.Obstacle)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::vutura::obstacles::Obstacle_Position* position_;
  ::vutura::obstacles::Obstacle_Fence* fence_;
  ::PROTOBUF_NAMESPACE_ID::uint32 id_;
  int type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_lora_2dobstacles_2eproto;
};
// -------------------------------------------------------------------

class CollisionWarning :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vutura.obstacles.CollisionWarning) */ {
 public:
  CollisionWarning();
  virtual ~CollisionWarning();

  CollisionWarning(const CollisionWarning& from);
  CollisionWarning(CollisionWarning&& from) noexcept
    : CollisionWarning() {
    *this = ::std::move(from);
  }

  inline CollisionWarning& operator=(const CollisionWarning& from) {
    CopyFrom(from);
    return *this;
  }
  inline CollisionWarning& operator=(CollisionWarning&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CollisionWarning& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CollisionWarning* internal_default_instance() {
    return reinterpret_cast<const CollisionWarning*>(
               &_CollisionWarning_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(CollisionWarning* other);
  friend void swap(CollisionWarning& a, CollisionWarning& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CollisionWarning* New() const final {
    return CreateMaybeMessage<CollisionWarning>(nullptr);
  }

  CollisionWarning* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CollisionWarning>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CollisionWarning& from);
  void MergeFrom(const CollisionWarning& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CollisionWarning* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vutura.obstacles.CollisionWarning";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_lora_2dobstacles_2eproto);
    return ::descriptor_table_lora_2dobstacles_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 timestamp = 1;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // uint32 ID = 2;
  void clear_id();
  static const int kIDFieldNumber = 2;
  ::PROTOBUF_NAMESPACE_ID::uint32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // float distance = 3;
  void clear_distance();
  static const int kDistanceFieldNumber = 3;
  float distance() const;
  void set_distance(float value);

  // @@protoc_insertion_point(class_scope:vutura.obstacles.CollisionWarning)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp_;
  ::PROTOBUF_NAMESPACE_ID::uint32 id_;
  float distance_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_lora_2dobstacles_2eproto;
};
// -------------------------------------------------------------------

class CollisionWarnings :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vutura.obstacles.CollisionWarnings) */ {
 public:
  CollisionWarnings();
  virtual ~CollisionWarnings();

  CollisionWarnings(const CollisionWarnings& from);
  CollisionWarnings(CollisionWarnings&& from) noexcept
    : CollisionWarnings() {
    *this = ::std::move(from);
  }

  inline CollisionWarnings& operator=(const CollisionWarnings& from) {
    CopyFrom(from);
    return *this;
  }
  inline CollisionWarnings& operator=(CollisionWarnings&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CollisionWarnings& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CollisionWarnings* internal_default_instance() {
    return reinterpret_cast<const CollisionWarnings*>(
               &_CollisionWarnings_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(CollisionWarnings* other);
  friend void swap(CollisionWarnings& a, CollisionWarnings& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CollisionWarnings* New() const final {
    return CreateMaybeMessage<CollisionWarnings>(nullptr);
  }

  CollisionWarnings* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CollisionWarnings>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CollisionWarnings& from);
  void MergeFrom(const CollisionWarnings& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CollisionWarnings* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vutura.obstacles.CollisionWarnings";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_lora_2dobstacles_2eproto);
    return ::descriptor_table_lora_2dobstacles_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .vutura.obstacles.CollisionWarning warningList = 1;
  int warninglist_size() const;
  void clear_warninglist();
  static const int kWarningListFieldNumber = 1;
  ::vutura::obstacles::CollisionWarning* mutable_warninglist(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vutura::obstacles::CollisionWarning >*
      mutable_warninglist();
  const ::vutura::obstacles::CollisionWarning& warninglist(int index) const;
  ::vutura::obstacles::CollisionWarning* add_warninglist();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vutura::obstacles::CollisionWarning >&
      warninglist() const;

  // @@protoc_insertion_point(class_scope:vutura.obstacles.CollisionWarnings)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vutura::obstacles::CollisionWarning > warninglist_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_lora_2dobstacles_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Empty

// -------------------------------------------------------------------

// TagsResponse

// repeated .vutura.obstacles.Obstacle obstacles = 1;
inline int TagsResponse::obstacles_size() const {
  return obstacles_.size();
}
inline void TagsResponse::clear_obstacles() {
  obstacles_.Clear();
}
inline ::vutura::obstacles::Obstacle* TagsResponse::mutable_obstacles(int index) {
  // @@protoc_insertion_point(field_mutable:vutura.obstacles.TagsResponse.obstacles)
  return obstacles_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vutura::obstacles::Obstacle >*
TagsResponse::mutable_obstacles() {
  // @@protoc_insertion_point(field_mutable_list:vutura.obstacles.TagsResponse.obstacles)
  return &obstacles_;
}
inline const ::vutura::obstacles::Obstacle& TagsResponse::obstacles(int index) const {
  // @@protoc_insertion_point(field_get:vutura.obstacles.TagsResponse.obstacles)
  return obstacles_.Get(index);
}
inline ::vutura::obstacles::Obstacle* TagsResponse::add_obstacles() {
  // @@protoc_insertion_point(field_add:vutura.obstacles.TagsResponse.obstacles)
  return obstacles_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vutura::obstacles::Obstacle >&
TagsResponse::obstacles() const {
  // @@protoc_insertion_point(field_list:vutura.obstacles.TagsResponse.obstacles)
  return obstacles_;
}

// -------------------------------------------------------------------

// Obstacle_Position

// float latitude = 1;
inline void Obstacle_Position::clear_latitude() {
  latitude_ = 0;
}
inline float Obstacle_Position::latitude() const {
  // @@protoc_insertion_point(field_get:vutura.obstacles.Obstacle.Position.latitude)
  return latitude_;
}
inline void Obstacle_Position::set_latitude(float value) {
  
  latitude_ = value;
  // @@protoc_insertion_point(field_set:vutura.obstacles.Obstacle.Position.latitude)
}

// float longitude = 2;
inline void Obstacle_Position::clear_longitude() {
  longitude_ = 0;
}
inline float Obstacle_Position::longitude() const {
  // @@protoc_insertion_point(field_get:vutura.obstacles.Obstacle.Position.longitude)
  return longitude_;
}
inline void Obstacle_Position::set_longitude(float value) {
  
  longitude_ = value;
  // @@protoc_insertion_point(field_set:vutura.obstacles.Obstacle.Position.longitude)
}

// float altitude = 3;
inline void Obstacle_Position::clear_altitude() {
  altitude_ = 0;
}
inline float Obstacle_Position::altitude() const {
  // @@protoc_insertion_point(field_get:vutura.obstacles.Obstacle.Position.altitude)
  return altitude_;
}
inline void Obstacle_Position::set_altitude(float value) {
  
  altitude_ = value;
  // @@protoc_insertion_point(field_set:vutura.obstacles.Obstacle.Position.altitude)
}

// -------------------------------------------------------------------

// Obstacle_Fence

// uint32 radius = 1;
inline void Obstacle_Fence::clear_radius() {
  radius_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Obstacle_Fence::radius() const {
  // @@protoc_insertion_point(field_get:vutura.obstacles.Obstacle.Fence.radius)
  return radius_;
}
inline void Obstacle_Fence::set_radius(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  radius_ = value;
  // @@protoc_insertion_point(field_set:vutura.obstacles.Obstacle.Fence.radius)
}

// uint32 min = 2;
inline void Obstacle_Fence::clear_min() {
  min_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Obstacle_Fence::min() const {
  // @@protoc_insertion_point(field_get:vutura.obstacles.Obstacle.Fence.min)
  return min_;
}
inline void Obstacle_Fence::set_min(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  min_ = value;
  // @@protoc_insertion_point(field_set:vutura.obstacles.Obstacle.Fence.min)
}

// uint32 max = 3;
inline void Obstacle_Fence::clear_max() {
  max_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Obstacle_Fence::max() const {
  // @@protoc_insertion_point(field_get:vutura.obstacles.Obstacle.Fence.max)
  return max_;
}
inline void Obstacle_Fence::set_max(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  max_ = value;
  // @@protoc_insertion_point(field_set:vutura.obstacles.Obstacle.Fence.max)
}

// -------------------------------------------------------------------

// Obstacle

// uint32 ID = 1;
inline void Obstacle::clear_id() {
  id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Obstacle::id() const {
  // @@protoc_insertion_point(field_get:vutura.obstacles.Obstacle.ID)
  return id_;
}
inline void Obstacle::set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:vutura.obstacles.Obstacle.ID)
}

// .vutura.obstacles.Obstacle.Type type = 2;
inline void Obstacle::clear_type() {
  type_ = 0;
}
inline ::vutura::obstacles::Obstacle_Type Obstacle::type() const {
  // @@protoc_insertion_point(field_get:vutura.obstacles.Obstacle.type)
  return static_cast< ::vutura::obstacles::Obstacle_Type >(type_);
}
inline void Obstacle::set_type(::vutura::obstacles::Obstacle_Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:vutura.obstacles.Obstacle.type)
}

// .vutura.obstacles.Obstacle.Position position = 3;
inline bool Obstacle::has_position() const {
  return this != internal_default_instance() && position_ != nullptr;
}
inline void Obstacle::clear_position() {
  if (GetArenaNoVirtual() == nullptr && position_ != nullptr) {
    delete position_;
  }
  position_ = nullptr;
}
inline const ::vutura::obstacles::Obstacle_Position& Obstacle::position() const {
  const ::vutura::obstacles::Obstacle_Position* p = position_;
  // @@protoc_insertion_point(field_get:vutura.obstacles.Obstacle.position)
  return p != nullptr ? *p : *reinterpret_cast<const ::vutura::obstacles::Obstacle_Position*>(
      &::vutura::obstacles::_Obstacle_Position_default_instance_);
}
inline ::vutura::obstacles::Obstacle_Position* Obstacle::release_position() {
  // @@protoc_insertion_point(field_release:vutura.obstacles.Obstacle.position)
  
  ::vutura::obstacles::Obstacle_Position* temp = position_;
  position_ = nullptr;
  return temp;
}
inline ::vutura::obstacles::Obstacle_Position* Obstacle::mutable_position() {
  
  if (position_ == nullptr) {
    auto* p = CreateMaybeMessage<::vutura::obstacles::Obstacle_Position>(GetArenaNoVirtual());
    position_ = p;
  }
  // @@protoc_insertion_point(field_mutable:vutura.obstacles.Obstacle.position)
  return position_;
}
inline void Obstacle::set_allocated_position(::vutura::obstacles::Obstacle_Position* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete position_;
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  position_ = position;
  // @@protoc_insertion_point(field_set_allocated:vutura.obstacles.Obstacle.position)
}

// .vutura.obstacles.Obstacle.Fence fence = 4;
inline bool Obstacle::has_fence() const {
  return this != internal_default_instance() && fence_ != nullptr;
}
inline void Obstacle::clear_fence() {
  if (GetArenaNoVirtual() == nullptr && fence_ != nullptr) {
    delete fence_;
  }
  fence_ = nullptr;
}
inline const ::vutura::obstacles::Obstacle_Fence& Obstacle::fence() const {
  const ::vutura::obstacles::Obstacle_Fence* p = fence_;
  // @@protoc_insertion_point(field_get:vutura.obstacles.Obstacle.fence)
  return p != nullptr ? *p : *reinterpret_cast<const ::vutura::obstacles::Obstacle_Fence*>(
      &::vutura::obstacles::_Obstacle_Fence_default_instance_);
}
inline ::vutura::obstacles::Obstacle_Fence* Obstacle::release_fence() {
  // @@protoc_insertion_point(field_release:vutura.obstacles.Obstacle.fence)
  
  ::vutura::obstacles::Obstacle_Fence* temp = fence_;
  fence_ = nullptr;
  return temp;
}
inline ::vutura::obstacles::Obstacle_Fence* Obstacle::mutable_fence() {
  
  if (fence_ == nullptr) {
    auto* p = CreateMaybeMessage<::vutura::obstacles::Obstacle_Fence>(GetArenaNoVirtual());
    fence_ = p;
  }
  // @@protoc_insertion_point(field_mutable:vutura.obstacles.Obstacle.fence)
  return fence_;
}
inline void Obstacle::set_allocated_fence(::vutura::obstacles::Obstacle_Fence* fence) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete fence_;
  }
  if (fence) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      fence = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, fence, submessage_arena);
    }
    
  } else {
    
  }
  fence_ = fence;
  // @@protoc_insertion_point(field_set_allocated:vutura.obstacles.Obstacle.fence)
}

// -------------------------------------------------------------------

// CollisionWarning

// uint64 timestamp = 1;
inline void CollisionWarning::clear_timestamp() {
  timestamp_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 CollisionWarning::timestamp() const {
  // @@protoc_insertion_point(field_get:vutura.obstacles.CollisionWarning.timestamp)
  return timestamp_;
}
inline void CollisionWarning::set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:vutura.obstacles.CollisionWarning.timestamp)
}

// uint32 ID = 2;
inline void CollisionWarning::clear_id() {
  id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CollisionWarning::id() const {
  // @@protoc_insertion_point(field_get:vutura.obstacles.CollisionWarning.ID)
  return id_;
}
inline void CollisionWarning::set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:vutura.obstacles.CollisionWarning.ID)
}

// float distance = 3;
inline void CollisionWarning::clear_distance() {
  distance_ = 0;
}
inline float CollisionWarning::distance() const {
  // @@protoc_insertion_point(field_get:vutura.obstacles.CollisionWarning.distance)
  return distance_;
}
inline void CollisionWarning::set_distance(float value) {
  
  distance_ = value;
  // @@protoc_insertion_point(field_set:vutura.obstacles.CollisionWarning.distance)
}

// -------------------------------------------------------------------

// CollisionWarnings

// repeated .vutura.obstacles.CollisionWarning warningList = 1;
inline int CollisionWarnings::warninglist_size() const {
  return warninglist_.size();
}
inline void CollisionWarnings::clear_warninglist() {
  warninglist_.Clear();
}
inline ::vutura::obstacles::CollisionWarning* CollisionWarnings::mutable_warninglist(int index) {
  // @@protoc_insertion_point(field_mutable:vutura.obstacles.CollisionWarnings.warningList)
  return warninglist_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vutura::obstacles::CollisionWarning >*
CollisionWarnings::mutable_warninglist() {
  // @@protoc_insertion_point(field_mutable_list:vutura.obstacles.CollisionWarnings.warningList)
  return &warninglist_;
}
inline const ::vutura::obstacles::CollisionWarning& CollisionWarnings::warninglist(int index) const {
  // @@protoc_insertion_point(field_get:vutura.obstacles.CollisionWarnings.warningList)
  return warninglist_.Get(index);
}
inline ::vutura::obstacles::CollisionWarning* CollisionWarnings::add_warninglist() {
  // @@protoc_insertion_point(field_add:vutura.obstacles.CollisionWarnings.warningList)
  return warninglist_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::vutura::obstacles::CollisionWarning >&
CollisionWarnings::warninglist() const {
  // @@protoc_insertion_point(field_list:vutura.obstacles.CollisionWarnings.warningList)
  return warninglist_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace obstacles
}  // namespace vutura

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::vutura::obstacles::Obstacle_Type> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::vutura::obstacles::Obstacle_Type>() {
  return ::vutura::obstacles::Obstacle_Type_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_lora_2dobstacles_2eproto
